# Generated by Django 5.1.3 on 2025-01-31 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 5, 0, 53, 184049, tzinfo=datetime.timezone.utc)),
        ),
    ]
