# Generated by Django 5.1.3 on 2025-02-06 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_forgotpassword_expire_date_chartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartmodel',
            name='dashboard_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartmodel',
            name='is_in_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 6, 11, 8, 990097, tzinfo=datetime.timezone.utc)),
        ),
    ]
