# Generated by Django 5.1.3 on 2025-02-06 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chartmodel_dashboard_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartmodel',
            name='dashboard_position',
        ),
        migrations.AlterField(
            model_name='forgotpassword',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 10, 36, 21, 213217, tzinfo=datetime.timezone.utc)),
        ),
    ]
